---

- hosts: all
  become: true
  tasks:


- hosts: web_servers
  become: true
  tasks:

  - name: install httpd server and php
    tags: php_web
    dnf:
      name:
        - "{{ web_package_name }}" 
        - "{{ php_package_name }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"
    register: apache

  - name: Start httpd services
    tags: php_web_start
    service:
      name: "{{ web_service }}"
      state: started
      enabled: yes
    when: apache.changed

  - name: Copy default.html file
    tags: copy_default_html
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

