---

- hosts: all
  become: true
  tasks:

  - name: update repository
    yum:
      update_cache: yes

  - name: install httpd server
    yum:
      name: httpd
      state: latest

  - name: install php
    yum:
      name: php
      state: latest
