 - name: add ssh keys for user
   tags: user_mgmt
   authorized_key:
     user: mantra
     key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGbS/Ho/3uxa4NjrcbKr/NXjwcsyvp/65lY3KGUiQh+C Ansibl_nokey"

 - name: generate sshd_config from template
   tags: ssh
   template: 
     src: "{{ ssh_template_file }}"
     dest: /etc/ssh/sshd_cofnig
     owner: root
     group: root
     mode: 0644
   notfiy: restart_sshd
